# KytyPS5 Performance & Settings Configuration
gpu-timestamp-scale = 125
ray-tracing = false
auto-optimize = false
master-volume = 100
audio-mute = false
aniso = 16
res-scale = 100
motion-blur = true
depth-of-field = true
bloom = true
ambient-occlusion = true
async-submit = true
pipeline-libraries = true
async-pipelines = true
relaxed-readback = true
speculative-draws = true
record-thread = true
hardware-buffer-bounds = true
osd-mode = 2
osd-alignment = 0
